const fs = require('fs');

const colorsToAdd = `
  --color-surface-container-high: #2a2a2c;
  --color-surface-container: #201f22;
  --color-on-tertiary-fixed-variant: #653e00;
  --color-secondary-container: #00a572;
  --color-surface-container-lowest: #0e0e10;
  --color-on-error: #690005;
  --color-tertiary-container: #ca8100;
  --color-primary-fixed-dim: #c0c1ff;
  --color-on-primary-container: #0d0096;
  --color-on-tertiary: #472a00;
  --color-surface-bright: #39393b;
  --color-on-background: #e5e1e4;
  --color-surface-container-highest: #353437;
  --color-on-tertiary-fixed: #2a1700;
  --color-on-secondary-fixed: #002113;
  --color-tertiary: #ffb95f;
  --color-on-primary: #1000a9;
  --color-on-surface: #e5e1e4;
  --color-on-tertiary-container: #3e2400;
  --color-surface-tint: #c0c1ff;
  --color-inverse-on-surface: #313032;
  --color-inverse-surface: #e5e1e4;
  --color-on-primary-fixed-variant: #2f2ebe;
  --color-on-primary-fixed: #07006c;
  --color-error: #ffb4ab;
  --color-inverse-primary: #494bd6;
  --color-tertiary-fixed-dim: #ffb95f;
  --color-surface-variant: #353437;
  --color-outline-variant: #464554;
  --color-secondary-fixed: #6ffbbe;
  --color-tertiary-fixed: #ffddb8;
  --color-primary-container: #8083ff;
  --color-outline: #908fa0;
  --color-surface: #131315;
  --color-error-container: #93000a;
  --color-surface-container-low: #1c1b1d;
  --color-on-secondary: #003824;
  --color-on-error-container: #ffdad6;
  --color-surface-dim: #131315;
  --color-on-secondary-fixed-variant: #005236;
  --color-primary-accent: #6366f1;
  --color-on-secondary-container: #00311f;
  --color-on-surface-variant: #c7c4d7;
  --color-secondary-fixed-dim: #4edea3;
  --color-primary-fixed: #e1e0ff;

  --font-headline-lg: "Geist", "sans-serif";
  --font-code-lg: "JetBrains Mono", "monospace";
  --font-display-hero: "Geist", "sans-serif";
  --font-label-mono-bold: "JetBrains Mono", "monospace";
  --font-body-sm: "Inter", "sans-serif";
  --font-label-mono: "JetBrains Mono", "monospace";
  --font-headline-sm: "Geist", "sans-serif";
  --font-body-md: "Inter", "sans-serif";
  --font-headline-md: "Geist", "sans-serif";
  --font-code-sm: "JetBrains Mono", "monospace";
  --font-body-lg: "Inter", "sans-serif";
`;

let css = fs.readFileSync('src/app/globals.css', 'utf8');
css = css.replace('@theme {', '@theme {' + colorsToAdd);
fs.writeFileSync('src/app/globals.css', css);
